### PR TITLE
Add Laravel 7.0 support

### PR DESCRIPTION
**Pull request by tkaratug**
Added Laravel 7.0 support

### CODE REVIEW

**Comment by blessingdube** [comment]
@tkaratug not sure if you need to add a reviewer so they get a notification?

**Comment by makroxyz** [comment]
Please merge the request

**Comment by mydnic** [comment]
@mpociot I think you forgot to tag a new release :) thanks in advance!

**Comment by rajendrap123** [comment]
@mpociot  can you pls do the new release? 

thanks in advance

**Comment by a-mazalov** [comment]
@mpociot сould you make a tag for the new release? thanks in advance!

**Comment by rajendrap123** [comment]
@mpociot  we are waiting...... :)

thanks in advance

**Comment by rajendrap123** [comment]
@mpociot any update on this?

your input on this will be highly appreciated

**Pull request merged**
