### PR TITLE
Added PHP 8 to composer.json

### PR DESCRIPTION
**Pull request by Edgarborras94**
Tested out with latest Laravel version (8.38) and PHP 8.

It worked with laravel octane too, but didn't tested it enough to assure it

### CODE REVIEW

**Review by CrazyBoy49z — APPROVED** [review]

**Comment by fawzanm** [comment]
I'd really appreciate if someone can merge this PR. This is the only dependency which prevents me from upgrading my project to PHP8.

**Comment by SerhiiMandrykin** [comment]
Guys, will it be ever merged ? :)

**Comment by neoighodaro** [comment]
Ping...

**Comment by CasperBE** [comment]
Here also the last package that keeps my project from upgrading to PHP 8.0, please merge this PR 🙏

**Comment by mohamedsabil83** [comment]
Waiting for merge this commit. 

CC: @mpociot, @sschlein, @mechelon

**Comment by mohamedsabil83** [comment]
Thank you @mpociot for merging. Can you add the new tag?

**Pull request merged**
